version: "3.4"
services:
  redmine:
    image: redmine:4.1.1
    restart: always
    ports:
      - 80:3000
    environment:
      TZ: Asia/Tokyo
      REDMINE_DB_MYSQL: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_DATABASE: redmine
      REDMINE_SECRET_KEY_BASE: redmine
    volumes:
      - ./config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./plugins:/usr/src/redmine/plugins
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
      MYSQL_DATABASE: redmine
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db:/var/lib/mysql

volumes:
  redmine:
  db:
